# Dagger workspace configuration
# Install modules with: dagger install <module>

[modules.e2e]
source = ".dagger/modules/e2e"

[modules.elixir-sdk]
source = "."
check.skip = ["*"]

[modules.dev]
source = ".dagger/modules/dev"

[modules.codegen]
source = "codegen"

[modules.sdk-sdk]
source = "github.com/dagger/sdk-sdk"

[sdks.elixir]
module = "elixir-sdk"

[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[sdks.dang]
module = "dagger-dang-sdk"

[sdks.dang.scopes."."]
is-module = true
name = "elixir-sdk"

[sdks.dang.scopes.".dagger/modules/dev"]
is-module = true

[sdks.dang.scopes.".dagger/modules/e2e"]
is-module = true

[sdks.dang.scopes.codegen]
is-module = true
