name = "elixir-sdk-runtime"
engineVersion = "v1.0.0-0"
include = ["../sdk/lib/**", "../sdk/mix.exs", "../sdk/mix.lock", "../sdk/.formatter.exs", "../sdk/LICENSE", "../sdk/dagger_codegen/**"]

[runtime]
  source = "dang"
