defmodule Dagger.Codegen.ElixirGenerator.RenderScalarTest do
  use Dagger.Codegen.RendererCase, async: true

  test "render scalar" do
    auto_assert(
      """
      # This file generated by `dagger_codegen`. Please DO NOT EDIT.
      defmodule Dagger.Platform do
        @moduledoc \"""
        The platform config OS and architecture in a Container.
        \"""

        use Dagger.Core.Base, kind: :scalar, name: "Platform"

        @type t() :: String.t()
      end\
      """ <- render_type("test/fixtures/scalars/platform.json")
    )
  end
end
