defmodule Dagger.Codegen.ElixirGenerator.RenderGuardsTest do
  use Dagger.Codegen.RendererCase, async: true

  @index %{
    "Directory" => %{kind: :object, enum_values: []},
    "Node" => %{kind: :interface, enum_values: []},
    "CacheSharingMode" => %{kind: :enum, enum_values: ["SHARED", "PRIVATE", "LOCKED"]}
  }

  test "every guardable argument shape" do
    auto_assert(
      """
      # This file generated by `dagger_codegen`. Please DO NOT EDIT.
      defmodule Dagger.Container do
        @moduledoc \"""
        An OCI-compatible container.
        \"""

        use Dagger.Core.Base, kind: :object, name: "Container"

        alias Dagger.Core.Client
        alias Dagger.Core.QueryBuilder, as: QB

        defstruct [:query_builder, :client]

        @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}

        @doc \"""
        Take one argument of every guardable shape.
        \"""
        @spec with_everything(
                t(),
                String.t(),
                integer(),
                boolean(),
                Dagger.JSON.t(),
                [String.t()],
                Dagger.Directory.t(),
                Dagger.Node.t(),
                Dagger.CacheSharingMode.t(),
                DateTime.t(),
                [{:owner, String.t()}]
              ) :: Dagger.Container.t()
        def with_everything(
              %__MODULE__{} = container,
              name,
              count,
              expand,
              config,
              args,
              %Dagger.Directory{} = source,
              object,
              sharing,
              at,
              optional_args \\\\ []
            )
            when is_binary(name) and is_integer(count) and is_boolean(expand) and is_binary(config) and
                   is_list(args) and is_struct(object) and sharing in [:SHARED, :PRIVATE, :LOCKED] and
                   is_struct(at, DateTime) do
          query_builder =
            container.query_builder
            |> QB.select("withEverything")
            |> QB.put_arg("name", name)
            |> QB.put_arg("count", count)
            |> QB.put_arg("expand", expand)
            |> QB.put_arg("config", config)
            |> QB.put_arg("args", args)
            |> QB.put_arg("source", Dagger.ID.id!(source))
            |> QB.put_arg("object", Dagger.ID.id!(object))
            |> QB.put_arg("sharing", sharing)
            |> QB.put_arg("at", at)
            |> QB.maybe_put_arg("owner", optional_args[:owner])

          %Dagger.Container{
            query_builder: query_builder,
            client: container.client
          }
        end
      end\
      """ <- render_type("test/fixtures/objects/guarded-args.json", @index)
    )
  end
end
