# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.Doc do
  @moduledoc """
  Doc contains " and \\
  """

  use Dagger.Core.Base, kind: :object, name: "Doc"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}

  @doc """
  Function doc contains " and \\
  """
  @spec doc_single_line(t()) :: {:ok, Dagger.TypeDefKind.t()} | {:error, term()}
  def doc_single_line(%__MODULE__{} = doc) do
    query_builder =
      doc.query_builder |> QB.select("doc_single_line")

    case Client.execute(doc.client, query_builder) do
      {:ok, enum} -> {:ok, Dagger.TypeDefKind.from_string(enum)}
      error -> error
    end
  end

  @doc """
  Function doc multiple line 
  contains " and \\
  """
  @spec doc_multi_line(t()) :: {:ok, Dagger.TypeDefKind.t()} | {:error, term()}
  def doc_multi_line(%__MODULE__{} = doc) do
    query_builder =
      doc.query_builder |> QB.select("doc_multi_line")

    case Client.execute(doc.client, query_builder) do
      {:ok, enum} -> {:ok, Dagger.TypeDefKind.from_string(enum)}
      error -> error
    end
  end
end
