# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.EnvVariable do
  @moduledoc """
  An environment variable name and value.
  """

  use Dagger.Core.Base, kind: :object, name: "EnvVariable"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client, :id]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t(), id: String.t() | nil}

  @doc """
  The environment variable name.
  """
  @spec name(t()) :: {:ok, String.t()} | {:error, term()}
  def name(%__MODULE__{} = env_variable) do
    query_builder =
      env_variable.query_builder |> QB.select("name")

    Client.execute(env_variable.client, query_builder)
  end
end
