# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.Client do
  @moduledoc """
  The root of the DAG.
  """

  use Dagger.Core.Base, kind: :object, name: "Query"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client, :id]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t(), id: String.t() | nil}

  @doc """
  Initializes a new environment

  > #### Experimental {: .warning}
  >
  > Environments are not yet stabilized
  """
  @spec env(t(), [{:privileged, boolean()}, {:writable, boolean()}]) :: Dagger.Env.t()
  def env(%__MODULE__{} = client, optional_args \\ []) do
    query_builder =
      client.query_builder
      |> QB.select("env",
        privileged: optional_args[:privileged],
        writable: optional_args[:writable]
      )

    %Dagger.Env{
      query_builder: query_builder,
      client: client.client
    }
  end
end
