# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.Module do
  @moduledoc """
  A Dagger module.
  """

  use Dagger.Core.Base, kind: :object, name: "Module"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  @derive Dagger.ID
  @derive Dagger.Sync
  defstruct [:query_builder, :client, :id]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t(), id: String.t() | nil}

  @doc """
  The dependencies of the module.
  """
  @spec dependencies(t()) :: {:ok, [Dagger.Module.t()]} | {:error, term()}
  def dependencies(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("dependencies") |> QB.select_fields(["id"])

    with {:ok, items} <- Client.execute(module.client, query_builder) do
      {:ok,
       for %{"id" => id} <- items do
         %Dagger.Module{
           query_builder:
             QB.query()
             |> QB.select("node", id: id)
             |> QB.inline_fragment("Module"),
           client: module.client
         }
       end}
    end
  end

  @doc """
  The doc string of the module, if any
  """
  @spec description(t()) :: {:ok, String.t()} | {:error, term()}
  def description(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("description")

    Client.execute(module.client, query_builder)
  end

  @doc """
  Enumerations served by this module.
  """
  @spec enums(t()) :: {:ok, [Dagger.TypeDef.t()]} | {:error, term()}
  def enums(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("enums") |> QB.select_fields(["id"])

    with {:ok, items} <- Client.execute(module.client, query_builder) do
      {:ok,
       for %{"id" => id} <- items do
         %Dagger.TypeDef{
           query_builder:
             QB.query()
             |> QB.select("node", id: id)
             |> QB.inline_fragment("TypeDef"),
           client: module.client
         }
       end}
    end
  end

  @doc """
  The generated files and directories made on top of the module source's context directory.
  """
  @spec generated_context_directory(t()) :: Dagger.Directory.t()
  def generated_context_directory(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("generatedContextDirectory")

    %Dagger.Directory{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  A unique identifier for this Module.
  """
  @spec id(t()) :: {:ok, String.t()} | {:error, term()}
  def id(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("id")

    Client.execute(module.client, query_builder)
  end

  @doc """
  Interfaces served by this module.
  """
  @spec interfaces(t()) :: {:ok, [Dagger.TypeDef.t()]} | {:error, term()}
  def interfaces(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("interfaces") |> QB.select_fields(["id"])

    with {:ok, items} <- Client.execute(module.client, query_builder) do
      {:ok,
       for %{"id" => id} <- items do
         %Dagger.TypeDef{
           query_builder:
             QB.query()
             |> QB.select("node", id: id)
             |> QB.inline_fragment("TypeDef"),
           client: module.client
         }
       end}
    end
  end

  @doc """
  The name of the module
  """
  @spec name(t()) :: {:ok, String.t()} | {:error, term()}
  def name(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("name")

    Client.execute(module.client, query_builder)
  end

  @doc """
  Objects served by this module.
  """
  @spec objects(t()) :: {:ok, [Dagger.TypeDef.t()]} | {:error, term()}
  def objects(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("objects") |> QB.select_fields(["id"])

    with {:ok, items} <- Client.execute(module.client, query_builder) do
      {:ok,
       for %{"id" => id} <- items do
         %Dagger.TypeDef{
           query_builder:
             QB.query()
             |> QB.select("node", id: id)
             |> QB.inline_fragment("TypeDef"),
           client: module.client
         }
       end}
    end
  end

  @doc """
  The container that runs the module's entrypoint. It will fail to execute if the module doesn't compile.
  """
  @spec runtime(t()) :: Dagger.Container.t() | nil
  def runtime(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("runtime")

    %Dagger.Container{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  The SDK config used by this module.
  """
  @spec sdk(t()) :: Dagger.SDKConfig.t() | nil
  def sdk(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("sdk")

    %Dagger.SDKConfig{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  Serve a module's API in the current session.

  Note: this can only be called once per session. In the future, it could return a stream or service to remove the side effect.
  """
  @spec serve(t(), [{:include_dependencies, boolean()}, {:entrypoint, boolean()}]) ::
          :ok | {:error, term()}
  def serve(%__MODULE__{} = module, optional_args \\ []) do
    query_builder =
      module.query_builder
      |> QB.select("serve",
        includeDependencies: optional_args[:include_dependencies],
        entrypoint: optional_args[:entrypoint]
      )

    case Client.execute(module.client, query_builder) do
      {:ok, _} -> :ok
      error -> error
    end
  end

  @doc """
  The source for the module.
  """
  @spec source(t()) :: Dagger.ModuleSource.t() | nil
  def source(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("source")

    %Dagger.ModuleSource{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  Forces evaluation of the module, including any loading into the engine and associated validation.
  """
  @spec sync(t()) :: {:ok, Dagger.Module.t()} | {:error, term()}
  def sync(%__MODULE__{} = module) do
    query_builder =
      module.query_builder |> QB.select("sync")

    with {:ok, id} <- Client.execute(module.client, query_builder) do
      {:ok,
       %Dagger.Module{
         query_builder:
           QB.query()
           |> QB.select("node", id: id)
           |> QB.inline_fragment("Module"),
         client: module.client
       }}
    end
  end

  @doc """
  Retrieves the module with the given description
  """
  @spec with_description(t(), String.t()) :: Dagger.Module.t()
  def with_description(%__MODULE__{} = module, description) when is_binary(description) do
    query_builder =
      module.query_builder |> QB.select("withDescription", description: description)

    %Dagger.Module{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  This module plus the given Enum type and associated values
  """
  @spec with_enum(t(), Dagger.TypeDef.t()) :: Dagger.Module.t()
  def with_enum(%__MODULE__{} = module, %Dagger.TypeDef{} = enum) do
    query_builder =
      module.query_builder |> QB.select("withEnum", enum: Dagger.ID.id!(enum))

    %Dagger.Module{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  This module plus the given Interface type and associated functions
  """
  @spec with_interface(t(), Dagger.TypeDef.t()) :: Dagger.Module.t()
  def with_interface(%__MODULE__{} = module, %Dagger.TypeDef{} = iface) do
    query_builder =
      module.query_builder |> QB.select("withInterface", iface: Dagger.ID.id!(iface))

    %Dagger.Module{
      query_builder: query_builder,
      client: module.client
    }
  end

  @doc """
  This module plus the given Object type and associated functions.
  """
  @spec with_object(t(), Dagger.TypeDef.t()) :: Dagger.Module.t()
  def with_object(%__MODULE__{} = module, %Dagger.TypeDef{} = object) do
    query_builder =
      module.query_builder |> QB.select("withObject", object: Dagger.ID.id!(object))

    %Dagger.Module{
      query_builder: query_builder,
      client: module.client
    }
  end
end

defimpl JSON.Encoder, for: Dagger.Module do
  def encode(module, encoder) do
    {:ok, id} = Dagger.Module.id(module)
    encoder.(id, encoder)
  end
end
