# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.Container do
  @moduledoc """
  An OCI-compatible container, also known as a Docker container.
  """

  use Dagger.Core.Base, kind: :object, name: "Container"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}

  @doc """
  Retrieves the list of environment variables passed to commands.
  """
  @spec env_variables(t()) :: {:ok, [Dagger.EnvVariable.t()]} | {:error, term()}
  def env_variables(%__MODULE__{} = container) do
    query_builder =
      container.query_builder |> QB.select("envVariables") |> QB.select_fields(["id"])

    with {:ok, items} <- Client.execute(container.client, query_builder) do
      {:ok,
       for %{"id" => id} <- items do
         %Dagger.EnvVariable{
           query_builder:
             QB.query()
             |> QB.select("node", id: id)
             |> QB.inline_fragment("EnvVariable"),
           client: container.client
         }
       end}
    end
  end
end
