# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.GhaSettings do
  @moduledoc """
  Dagger.GhaSettings
  """

  use Dagger.Core.Base, kind: :object, name: "GhaSettings"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}

  @spec permissions(t()) :: {:ok, [Dagger.GhaPermission.t()]} | {:error, term()}
  def permissions(%__MODULE__{} = gha_settings) do
    query_builder =
      gha_settings.query_builder |> QB.select("permissions")

    case Client.execute(gha_settings.client, query_builder) do
      {:ok, enums} -> {:ok, Enum.map(enums, &Dagger.GhaPermission.from_string/1)}
      error -> error
    end
  end
end
