# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.FunctionCall do
  @moduledoc """
  An active function call.
  """

  use Dagger.Core.Base, kind: :object, name: "FunctionCall"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}

  @doc """
  Set the return value of the function call to the provided value.
  """
  @spec return_value(t(), Dagger.JSON.t()) :: :ok | {:error, term()}
  def return_value(%__MODULE__{} = function_call, value) when is_binary(value) do
    query_builder =
      function_call.query_builder |> QB.select("returnValue", value: value)

    case Client.execute(function_call.client, query_builder) do
      {:ok, _} -> :ok
      error -> error
    end
  end
end
