# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.TypeDef do
  @moduledoc """
  A definition of a parameter or return type in a Module.
  """

  use Dagger.Core.Base, kind: :object, name: "TypeDef"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client, :id]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t(), id: String.t() | nil}

  @doc """
  The kind of type this is (e.g. primitive, list, object).
  """
  @spec kind(t()) :: {:ok, Dagger.TypeDefKind.t()} | {:error, term()}
  def kind(%__MODULE__{} = type_def) do
    query_builder =
      type_def.query_builder |> QB.select("kind")

    case Client.execute(type_def.client, query_builder) do
      {:ok, enum} -> {:ok, Dagger.TypeDefKind.from_string(enum)}
      error -> error
    end
  end
end
