# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.Platform do
  @moduledoc """
  The platform config OS and architecture in a Container.
  """

  use Dagger.Core.Base, kind: :scalar, name: "Platform"

  @type t() :: String.t()
end
