defmodule Dagger.Codegen.RenderInputTest do
  use Dagger.Codegen.RendererCase, async: true

  test "render input object" do
    auto_assert(
      """
      # This file generated by `dagger_codegen`. Please DO NOT EDIT.
      defmodule Dagger.BuildArg do
        @moduledoc \"""
        Key value object that represents a build argument.
        \"""

        use Dagger.Core.Base, kind: :input, name: "BuildArg"

        @type t() :: %__MODULE__{name: String.t(), value: String.t()}

        @enforce_keys [:name, :value]

        defstruct [:name, :value]
      end\
      """ <- render_type("test/fixtures/inputs/build-arg.json")
    )
  end
end
