defmodule Dagger.Codegen.Render do
  @moduledoc """
  Prints a `ModuleDef` as Elixir source.

  Nothing here decides anything — every branch is a shape already chosen by the
  analyzer. Indentation is deliberately ignored: the output goes through
  `Code.format_string!/1`, so each shape can be written as a plain heredoc.
  """

  alias Dagger.Codegen.IR.Arg
  alias Dagger.Codegen.IR.EnumValue
  alias Dagger.Codegen.IR.Function
  alias Dagger.Codegen.IR.ModuleDef
  alias Dagger.Codegen.Naming
  alias Dagger.Codegen.Type

  @header "# This file generated by `dagger_codegen`. Please DO NOT EDIT."

  @doc """
  Render a module definition into iodata.
  """
  def render(%ModuleDef{} = mod) do
    [
      @header,
      ?\n,
      "defmodule #{mod.module} do",
      ?\n,
      "@moduledoc ",
      heredoc(mod.moduledoc),
      ?\n,
      ?\n,
      body(mod),
      "end",
      protocols(mod)
    ]
  end

  ## Module bodies

  defp body(%ModuleDef{kind: kind} = mod) when kind in [:object, :interface] do
    [
      """
      use Dagger.Core.Base, kind: :#{kind}, name: "#{mod.gql_name}"

      alias Dagger.Core.Client
      alias Dagger.Core.QueryBuilder, as: QB
      """,
      ?\n,
      Enum.map_intersperse(mod.derives, ?\n, &["@derive ", &1]),
      ?\n,
      "defstruct [:query_builder, :client]",
      ?\n,
      ?\n,
      "@type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}",
      ?\n,
      Enum.map(mod.functions, &[function(&1, mod), ?\n])
    ]
  end

  defp body(%ModuleDef{kind: :enum} = mod) do
    [
      """
      use Dagger.Core.Base, kind: :enum, name: "#{mod.gql_name}"
      """,
      ?\n,
      ?\n,
      "@type t() :: ",
      Enum.map_intersperse(mod.enum_values, " | ", &[?:, &1.value]),
      ?\n,
      ?\n,
      mod.enum_values |> Enum.uniq_by(& &1.name) |> Enum.map(&[enum_value(&1), ?\n, ?\n]),
      ?\n,
      ?\n,
      """
      @doc false
      @spec from_string(String.t()) :: t()
      def from_string(string)
      """,
      ?\n,
      ?\n,
      Enum.map(mod.enum_values, &"def from_string(\"#{&1.value}\"), do: :#{&1.value}\n"),
      ?\n,
      ?\n
    ]
  end

  defp body(%ModuleDef{kind: :input} = mod) do
    [
      """
      use Dagger.Core.Base, kind: :input, name: "#{mod.gql_name}"
      """,
      ?\n,
      ?\n,
      "@type t() :: %__MODULE__{",
      Enum.map_intersperse(mod.fields, ",", &[&1.name, ": ", Type.spec(&1.type)]),
      ?\n,
      "}",
      ?\n,
      ?\n,
      enforce_keys(mod.fields),
      "defstruct [",
      Enum.map_intersperse(mod.fields, ",", &[?:, &1.name]),
      "]"
    ]
  end

  defp body(%ModuleDef{kind: :scalar} = mod) do
    [
      """
      use Dagger.Core.Base, kind: :scalar, name: "#{mod.gql_name}"
      """,
      ?\n,
      ?\n,
      "@type t() :: String.t()"
    ]
  end

  defp enforce_keys(fields) do
    case Enum.reject(fields, &Type.nullable?(&1.type)) do
      [] ->
        []

      required ->
        ["@enforce_keys [", Enum.map_intersperse(required, ",", &[?:, &1.name]), "]\n\n"]
    end
  end

  ## Enums

  defp enum_value(%EnumValue{} = value) do
    [
      doc(value.doc),
      ?\n,
      "@spec #{value.name}() :: :#{value.value}",
      ?\n,
      "def #{value.name}(), do: :#{value.value}"
    ]
  end

  ## Object functions

  defp function(%Function{} = fun, %ModuleDef{} = mod) do
    [
      deprecated(fun.deprecated),
      ?\n,
      doc(fun.doc),
      ?\n,
      spec(fun),
      ?\n,
      "def #{fun.name}(",
      head_args(fun),
      ")",
      guards(fun),
      " do",
      ?\n,
      "  query_builder = ",
      ?\n,
      query_builder(fun),
      ?\n,
      execute(fun, mod),
      ?\n,
      "end"
    ]
  end

  defp head_args(%Function{} = fun) do
    [
      "%__MODULE__{} =",
      fun.self,
      Enum.map(fun.required_args, &[",", pattern(&1)]),
      if(fun.optional_args == [], do: [], else: ", optional_args \\\\ []")
    ]
  end

  # A struct argument is narrowed by matching it; everything else by a guard.
  defp pattern(%Arg{guard: {:struct, module}} = arg), do: "%#{module}{} = #{arg.name}"
  defp pattern(%Arg{} = arg), do: arg.name

  defp guards(%Function{} = fun) do
    case Enum.flat_map(fun.required_args, &List.wrap(guard(&1))) do
      [] -> []
      guards -> [" when ", Enum.intersperse(guards, " and ")]
    end
  end

  defp guard(%Arg{guard: {:call, fun}} = arg), do: "#{fun}(#{arg.name})"
  defp guard(%Arg{guard: {:is_struct, module}} = arg), do: "is_struct(#{arg.name}, #{module})"
  defp guard(%Arg{guard: {:in, values}} = arg), do: "#{arg.name} in [#{Enum.join(values, ", ")}]"
  defp guard(%Arg{}), do: nil

  defp spec(%Function{} = fun) do
    [
      "@spec #{fun.name}(t()",
      Enum.map(fun.required_args, &[",", Type.spec(&1.type)]),
      optional_args_spec(fun.optional_args),
      ") :: ",
      return_spec(fun.return)
    ]
  end

  defp optional_args_spec([]), do: []

  defp optional_args_spec(args) do
    [
      ",[",
      Enum.map_intersperse(
        args,
        ",",
        &["{:", &1.name, ",", Type.spec(Type.non_null(&1.type)), "}"]
      ),
      "]"
    ]
  end

  defp return_spec({:lazy, type}), do: Type.spec(type)
  defp return_spec(:void), do: ":ok | {:error, term()}"
  defp return_spec({:node, name}), do: ok(Naming.module(name) <> ".t()")
  defp return_spec({_kind, type}), do: ok(Type.spec(type))

  defp ok(spec), do: "{:ok, #{spec}} | {:error, term()}"

  ## Query building

  defp query_builder(%Function{} = fun) do
    [
      "#{fun.self}.query_builder",
      "|> QB.select(\"#{fun.gql_name}\")",
      Enum.map(fun.required_args, &["|> QB.put_arg(\"#{&1.gql_name}\", ", put_arg(&1), ")"]),
      Enum.map(
        fun.optional_args,
        &["|> QB.maybe_put_arg(\"#{&1.gql_name}\", ", maybe_put_arg(&1), ")"]
      ),
      # A list of objects is fetched by id, then rehydrated client-side.
      case fun.return do
        {:nodes, _type} -> "|> QB.select(\"id\")"
        _otherwise -> []
      end
    ]
  end

  defp put_arg(%Arg{} = arg) do
    case Type.encoder(arg.type) do
      :identity -> arg.name
      {:call, fun} -> "#{fun}(#{arg.name})"
      {:map, fun} -> "Enum.map(#{arg.name}, &#{fun}/1)"
    end
  end

  defp maybe_put_arg(%Arg{} = arg) do
    value = "optional_args[:#{arg.name}]"

    case Type.encoder(arg.type) do
      :identity -> value
      {:call, fun} -> "if(#{value}, do: #{fun}(#{value}), else: nil)"
      {:map, fun} -> "if(#{value}, do: Enum.map(#{value}, &#{fun}/1), else: nil)"
    end
  end

  ## Executing

  defp execute(%Function{return: {:lazy, type}} = fun, _mod) do
    """
    %#{Type.module(type)}{
      query_builder: query_builder,
      client: #{fun.self}.client
    }
    """
  end

  defp execute(%Function{return: {:leaf, _type}} = fun, _mod) do
    "Client.execute(#{fun.self}.client, query_builder)"
  end

  defp execute(%Function{return: :void} = fun, _mod) do
    """
    case Client.execute(#{fun.self}.client, query_builder) do
      {:ok, _} -> :ok
      error -> error
    end
    """
  end

  defp execute(%Function{return: {:enum, type}} = fun, _mod) do
    """
    case Client.execute(#{fun.self}.client, query_builder) do
      {:ok, enum} -> {:ok, #{Type.module(type)}.from_string(enum)}
      error -> error
    end
    """
  end

  defp execute(%Function{return: {:list_of_enum, type}} = fun, _mod) do
    """
    case Client.execute(#{fun.self}.client, query_builder) do
      {:ok, enums} -> {:ok, Enum.map(enums, &#{Type.module(type)}.from_string/1)}
      error -> error
    end
    """
  end

  defp execute(%Function{return: {:nodes, type}} = fun, _mod) do
    {_kind, gql_name} = Type.element(type)

    """
    with {:ok, items} <- Client.execute(#{fun.self}.client, query_builder) do
      {:ok, for %{"id" => id} <- items do
        #{node_struct(Naming.module(gql_name), gql_name, "QB.query()", "#{fun.self}.client")}
      end}
    end
    """
  end

  defp execute(%Function{return: {:node, gql_name}} = fun, _mod) do
    """
    with {:ok, id} <- Client.execute(#{fun.self}.client, query_builder) do
      {:ok, #{node_struct(Naming.module(gql_name), gql_name, "QB.query()", "#{fun.self}.client")}}
    end
    """
  end

  # A struct that resolves back to a node by id, used wherever the API hands us
  # an id instead of a selection.
  defp node_struct(module, gql_name, base, client) do
    """
    %#{module}{
      query_builder:
        #{base}
        |> QB.select("node")
        |> QB.put_arg("id", id)
        |> QB.inline_fragment("#{gql_name}"),
      client: #{client}
    }\
    """
  end

  ## Protocol implementations

  defp protocols(%ModuleDef{} = mod) do
    if ModuleDef.node?(mod) do
      [
        ?\n,
        """
        defimpl Jason.Encoder, for: #{mod.module} do
          def encode(#{mod.var}, opts) do
            {:ok, id} = #{mod.module}.id(#{mod.var})
            Jason.Encode.string(id, opts)
          end
        end
        """,
        ?\n,
        """
        defimpl Nestru.Decoder, for: #{mod.module} do
          def decode_fields_hint(_struct, _context, id) do
            alias Dagger.Core.QueryBuilder, as: QB
            dag = Dagger.Global.dag()
            {:ok, #{node_struct(mod.module, mod.gql_name, "dag.query_builder", "dag.client")}}
          end
        end
        """
      ]
    else
      []
    end
  end

  ## Documentation

  defp doc(nil), do: ""
  defp doc(text), do: ["@doc ", heredoc(text)]

  defp deprecated(nil), do: ""
  defp deprecated(text), do: ["@deprecated ", heredoc(text)]

  defp heredoc(text) do
    ["\"\"\"", ?\n, escape(text), ?\n, "\"\"\""]
  end

  defp escape(text), do: String.replace(text, "\\", "\\\\")
end
