//! Prints a `ModuleDef` as readable Elixir source, a port of
//! `Dagger.Codegen.Render` that lays the code out itself instead of relying on
//! `Code.format_string!/1`.
//!
//! The layout follows `mix format`'s house style. Constructs that can outgrow a
//! line (specs, function heads, the query pipeline, type and struct lists) are
//! printed on one line when they fit in `line_length` columns and in the
//! formatter's broken shape otherwise. This is not a formatter: it only knows
//! the handful of shapes the generator emits.

const std = @import("std");
const Allocator = std.mem.Allocator;
const Writer = std.Io.Writer;
const analyzer = @import("analyzer.zig");
const naming = @import("naming.zig");
const types = @import("types.zig");
const ModuleDef = analyzer.ModuleDef;
const Function = analyzer.Function;
const Arg = analyzer.Arg;

/// `mix format`'s default.
const line_length = 98;

const header = "# This file generated by `dagger_codegen`. Please DO NOT EDIT.";

/// A scratch buffer for building one candidate line, to measure it before
/// deciding between the one-line and the broken layout.
const Line = struct {
    buf: Writer.Allocating,

    fn init(a: Allocator) Line {
        return .{ .buf = .init(a) };
    }

    fn w(self: *Line) *Writer {
        return &self.buf.writer;
    }

    fn text(self: *Line) []const u8 {
        return self.buf.written();
    }

    fn fits(self: *Line, indent: usize) bool {
        return indent + self.text().len <= line_length;
    }
};

fn pad(w: *Writer, indent: usize) !void {
    try w.splatByteAll(' ', indent);
}

pub fn render(a: Allocator, w: *Writer, mod: *const ModuleDef) !void {
    try w.print("{s}\ndefmodule {s} do\n", .{ header, mod.module });
    try heredoc(w, 2, "@moduledoc ", mod.moduledoc);
    try w.writeByte('\n');
    switch (mod.kind) {
        .object, .interface => try objectBody(a, w, mod),
        .@"enum" => try enumBody(a, w, mod),
        .input => try inputBody(a, w, mod),
        .scalar => try w.print(
            "  use Dagger.Core.Base, kind: :scalar, name: \"{s}\"\n\n  @type t() :: String.t()\n",
            .{mod.gql_name},
        ),
        .unknown => return error.UnsupportedType,
    }
    try w.writeAll("end\n");
    if (mod.isNode()) try protocols(a, w, mod);
}

// -- Module bodies -----------------------------------------------------------

fn objectBody(a: Allocator, w: *Writer, mod: *const ModuleDef) !void {
    try w.print(
        \\  use Dagger.Core.Base, kind: :{t}, name: "{s}"
        \\
        \\  alias Dagger.Core.Client
        \\  alias Dagger.Core.QueryBuilder, as: QB
        \\
        \\
    , .{ mod.kind, mod.gql_name });
    for (mod.derives) |d| try w.print("  @derive {s}\n", .{d});
    try w.writeAll(
        \\  defstruct [:query_builder, :client]
        \\
        \\  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}
        \\
    );
    for (mod.functions) |*f| {
        try w.writeByte('\n');
        try function(a, w, f);
    }
}

fn enumBody(a: Allocator, w: *Writer, mod: *const ModuleDef) !void {
    try w.print("  use Dagger.Core.Base, kind: :enum, name: \"{s}\"\n\n", .{mod.gql_name});

    var line = Line.init(a);
    try line.w().writeAll("@type t() :: ");
    for (mod.enum_values, 0..) |v, i| {
        if (i > 0) try line.w().writeAll(" | ");
        try line.w().print(":{s}", .{v.value});
    }
    const union_text = line.text()["@type t() :: ".len..];
    if (line.fits(2)) {
        try w.print("  {s}\n", .{line.text()});
    } else if (10 + union_text.len <= line_length) {
        try w.print("  @type t() ::\n          {s}\n", .{union_text});
    } else {
        try w.writeAll("  @type t() ::\n");
        for (mod.enum_values, 0..) |v, i| {
            try w.print("          {s}:{s}\n", .{ if (i > 0) "| " else "", v.value });
        }
    }

    // `Enum.uniq_by(& &1.name)`: the first member with a given name wins.
    for (mod.enum_values, 0..) |v, i| {
        const seen = for (mod.enum_values[0..i]) |prev| {
            if (std.mem.eql(u8, prev.name, v.name)) break true;
        } else false;
        if (seen) continue;
        try w.writeByte('\n');
        if (v.doc) |d| try heredoc(w, 2, "@doc ", d);
        try w.print("  @spec {0s}() :: :{1s}\n  def {0s}(), do: :{1s}\n", .{ v.name, v.value });
    }

    try w.writeAll(
        \\
        \\  @doc false
        \\  @spec from_string(String.t()) :: t()
        \\  def from_string(string)
        \\
        \\
    );
    for (mod.enum_values) |v| try w.print("  def from_string(\"{0s}\"), do: :{0s}\n", .{v.value});
}

fn inputBody(a: Allocator, w: *Writer, mod: *const ModuleDef) !void {
    try w.print("  use Dagger.Core.Base, kind: :input, name: \"{s}\"\n\n", .{mod.gql_name});

    var line = Line.init(a);
    try line.w().writeAll("@type t() :: %__MODULE__{");
    for (mod.fields, 0..) |f, i| {
        if (i > 0) try line.w().writeAll(", ");
        try line.w().print("{s}: ", .{f.name});
        try types.spec(a, line.w(), f.type);
    }
    try line.w().writeByte('}');
    if (line.fits(2)) {
        try w.print("  {s}\n", .{line.text()});
    } else {
        try w.writeAll("  @type t() :: %__MODULE__{\n");
        for (mod.fields, 0..) |f, i| {
            try w.print("          {s}: ", .{f.name});
            try types.spec(a, w, f.type);
            try w.writeAll(if (i + 1 < mod.fields.len) ",\n" else "\n");
        }
        try w.writeAll("        }\n");
    }

    var required: std.ArrayList([]const u8) = .empty;
    var all: std.ArrayList([]const u8) = .empty;
    for (mod.fields) |f| {
        try all.append(a, f.name);
        if (!types.isNullable(f.type)) try required.append(a, f.name);
    }
    if (required.items.len > 0) {
        try w.writeByte('\n');
        try atomList(a, w, "@enforce_keys ", required.items);
    }
    try w.writeByte('\n');
    try atomList(a, w, "defstruct ", all.items);
}

/// `prefix[:a, :b]`, or one atom per line when that does not fit.
fn atomList(a: Allocator, w: *Writer, prefix: []const u8, names: []const []const u8) !void {
    var line = Line.init(a);
    try line.w().print("{s}[", .{prefix});
    for (names, 0..) |n, i| try line.w().print("{s}:{s}", .{ if (i > 0) ", " else "", n });
    try line.w().writeByte(']');
    if (line.fits(2)) return w.print("  {s}\n", .{line.text()});
    try w.print("  {s}[\n", .{prefix});
    for (names, 0..) |n, i| try w.print("    :{s}{s}\n", .{ n, if (i + 1 < names.len) "," else "" });
    try w.writeAll("  ]\n");
}

// -- Object functions --------------------------------------------------------

fn function(a: Allocator, w: *Writer, f: *const Function) !void {
    if (f.deprecated) |d| try heredoc(w, 2, "@deprecated ", d);
    if (f.doc) |d| try heredoc(w, 2, "@doc ", d);
    try spec(a, w, f);
    try head(a, w, f);
    try w.writeAll("    query_builder =\n");
    try pipeline(a, w, f);
    try w.writeByte('\n');
    try execute(a, w, f);
    try w.writeAll("  end\n");
}

fn spec(a: Allocator, w: *Writer, f: *const Function) !void {
    var ret = Line.init(a);
    try returnSpec(a, ret.w(), f.@"return");

    var params: std.ArrayList([]const u8) = .empty;
    try params.append(a, "t()");
    for (f.required_args) |arg| {
        var p = Line.init(a);
        try types.spec(a, p.w(), arg.type);
        try params.append(a, p.text());
    }
    var optional = Line.init(a);
    if (f.optional_args.len > 0) {
        try optional.w().writeByte('[');
        for (f.optional_args, 0..) |arg, i| {
            if (i > 0) try optional.w().writeAll(", ");
            try optionalSpec(a, optional.w(), arg);
        }
        try optional.w().writeByte(']');
        try params.append(a, optional.text());
    }

    var call = Line.init(a);
    try call.w().print("@spec {s}(", .{f.name});
    for (params.items, 0..) |p, i| try call.w().print("{s}{s}", .{ if (i > 0) ", " else "", p });
    try call.w().writeByte(')');

    // 1. Everything on one line.
    if (2 + call.text().len + 4 + ret.text().len <= line_length) {
        return w.print("  {s} :: {s}\n", .{ call.text(), ret.text() });
    }
    // 2. Break after `::`. The formatter measures the call without the ` ::`,
    // and lets a trailing keyword list hang one column further.
    const hang: usize = if (f.optional_args.len > 0) 1 else 0;
    if (2 + call.text().len <= line_length + hang and 10 + ret.text().len <= line_length) {
        return w.print("  {s} ::\n          {s}\n", .{ call.text(), ret.text() });
    }
    // 3. Break the trailing keyword list, one entry per line, when the line
    // that opens it fits.
    var opening = Line.init(a);
    try opening.w().print("@spec {s}(", .{f.name});
    for (params.items[0 .. params.items.len - 1]) |p| try opening.w().print("{s}, ", .{p});
    try opening.w().writeByte('[');
    if (f.optional_args.len > 0 and opening.fits(2)) {
        try w.print("  {s}\n", .{opening.text()});
        for (f.optional_args, 0..) |arg, i| {
            try pad(w, 10);
            try optionalSpec(a, w, arg);
            try w.writeAll(if (i + 1 < f.optional_args.len) ",\n" else "\n");
        }
        return w.print("        ]) :: {s}\n", .{ret.text()});
    }
    // 4. One argument per line.
    try w.print("  @spec {s}(\n", .{f.name});
    for (params.items, 0..) |p, i| try w.print("          {s}{s}\n", .{ p, if (i + 1 < params.items.len) "," else "" });
    try w.print("        ) :: {s}\n", .{ret.text()});
}

fn optionalSpec(a: Allocator, w: *Writer, arg: Arg) !void {
    try w.print("{{:{s}, ", .{arg.name});
    try types.spec(a, w, types.nonNull(arg.type));
    try w.writeByte('}');
}

fn returnSpec(a: Allocator, w: *Writer, ret: analyzer.Return) !void {
    switch (ret) {
        .lazy => |t| try types.spec(a, w, t),
        .void => try w.writeAll(":ok | {:error, term()}"),
        .node => |name| try w.print("{{:ok, {s}.t()}} | {{:error, term()}}", .{try naming.module(a, name)}),
        inline .leaf, .@"enum", .list_of_enum, .nodes => |t| {
            try w.writeAll("{:ok, ");
            try types.spec(a, w, t);
            try w.writeAll("} | {:error, term()}");
        },
    }
}

fn head(a: Allocator, w: *Writer, f: *const Function) !void {
    var params: std.ArrayList([]const u8) = .empty;
    try params.append(a, try std.fmt.allocPrint(a, "%__MODULE__{{}} = {s}", .{f.self}));
    for (f.required_args) |arg| try params.append(a, switch (arg.guard) {
        .@"struct" => |m| try std.fmt.allocPrint(a, "%{s}{{}} = {s}", .{ m, arg.name }),
        else => arg.name,
    });
    if (f.optional_args.len > 0) try params.append(a, "optional_args \\\\ []");

    var call = Line.init(a);
    try call.w().print("def {s}(", .{f.name});
    for (params.items, 0..) |p, i| try call.w().print("{s}{s}", .{ if (i > 0) ", " else "", p });
    try call.w().writeByte(')');

    const parts = try guardParts(a, f);
    var guard = Line.init(a);
    for (parts, 0..) |part, i| try guard.w().print("{s}{s}", .{ if (i > 0) " and " else "", part.text });

    // With a guard the whole line, ` do` included, has to fit; without one the
    // formatter measures the head alone.
    const one_line = if (parts.len > 0) 2 + call.text().len + 6 + guard.text().len + 3 else 2 + call.text().len;
    if (one_line <= line_length) {
        try w.print("  {s}", .{call.text()});
        if (parts.len > 0) try w.print(" when {s}", .{guard.text()});
        return w.writeAll(" do\n");
    }
    if (call.fits(2)) {
        try w.print("  {s}\n", .{call.text()});
    } else {
        try w.print("  def {s}(\n", .{f.name});
        for (params.items, 0..) |p, i| try w.print("        {s}{s}\n", .{ p, if (i + 1 < params.items.len) "," else "" });
        try w.writeAll("      )");
        if (parts.len == 0) return w.writeAll(" do\n");
        try w.writeByte('\n');
    }
    try whenClause(w, parts, guard.text());
}

/// One conjunct of a function guard. `in` guards keep their members so a long
/// list can be broken one member per line.
const GuardPart = struct {
    text: []const u8,
    in_name: []const u8 = "",
    in_values: []const []const u8 = &.{},
};

fn guardParts(a: Allocator, f: *const Function) ![]const GuardPart {
    var parts: std.ArrayList(GuardPart) = .empty;
    for (f.required_args) |arg| try parts.append(a, switch (arg.guard) {
        .none, .@"struct" => continue,
        .call => |fun| .{ .text = try std.fmt.allocPrint(a, "{s}({s})", .{ fun, arg.name }) },
        .is_struct => |m| .{ .text = try std.fmt.allocPrint(a, "is_struct({s}, {s})", .{ arg.name, m }) },
        .in => |values| .{
            .text = try std.fmt.allocPrint(a, "{s} in [{s}]", .{ arg.name, try std.mem.join(a, ", ", values) }),
            .in_name = arg.name,
            .in_values = values,
        },
        .@"enum" => unreachable,
    });
    return parts.items;
}

/// `when ... do` on its own line under a function head. Too long, conjuncts
/// fill each line greedily, continuing at column 13. As elsewhere, the ` and`
/// or ` do` that trails a conjunct does not count against the line. A
/// conjunct that does not fit even on a fresh line is an `in` guard whose list
/// is broken one member per line where it stands.
fn whenClause(w: *Writer, parts: []const GuardPart, flat: []const u8) !void {
    if (6 + 5 + flat.len <= line_length) return w.print("      when {s} do\n", .{flat});

    try w.writeAll("      when ");
    var col: usize = 6 + 5;
    var line_start = true;
    for (parts, 0..) |part, i| {
        const last = i + 1 == parts.len;
        const tail: []const u8 = if (last) "" else " and";
        const sep: usize = if (line_start) 0 else 1;
        if (!line_start and col + sep + part.text.len > line_length) {
            try w.writeAll("\n             ");
            col = 13;
            line_start = true;
        } else if (!line_start) {
            try w.writeByte(' ');
            col += 1;
        }
        if (part.in_values.len > 0 and col + part.text.len > line_length) {
            try w.print("{s} in [\n", .{part.in_name});
            for (part.in_values, 0..) |v, j| {
                try pad(w, col + 2);
                try w.print("{s}{s}\n", .{ v, if (j + 1 < part.in_values.len) "," else "" });
            }
            try pad(w, col);
            try w.writeByte(']');
            col += 1;
        } else {
            try w.writeAll(part.text);
            col += part.text.len;
        }
        try w.writeAll(if (last) " do\n" else " and");
        col += tail.len;
        line_start = false;
    }
}

// -- Query building ----------------------------------------------------------

const select_fields = "|> QB.select_fields([\"id\"])";

/// One `key: value` argument to `QB.select/3`. An optional argument that has
/// to be encoded is `if(cond, do: then, else: nil)`, which the formatter splits
/// across lines when it does not fit.
const Entry = struct {
    key: []const u8,
    value: []const u8,
    cond: ?[]const u8 = null,
    then: []const u8 = "",

    fn write(e: Entry, w: *Writer, indent: usize, last: bool) !void {
        const comma: []const u8 = if (last) "" else ",";
        if (indent + e.key.len + 2 + e.value.len + comma.len <= line_length) {
            return w.print("{s}: {s}{s}\n", .{ e.key, e.value, comma });
        }
        try w.print("{s}:\n", .{e.key});
        try pad(w, indent + 2);
        const cond = e.cond orelse return w.print("{s}{s}\n", .{ e.value, comma });
        // On its own line the value is measured without its trailing comma.
        if (indent + 2 + e.value.len <= line_length) {
            return w.print("{s}{s}\n", .{ e.value, comma });
        }
        try w.print("if({s},\n", .{cond});
        try pad(w, indent + 4);
        try w.print("do: {s},\n", .{e.then});
        try pad(w, indent + 4);
        try w.writeAll("else: nil\n");
        try pad(w, indent + 2);
        try w.print("){s}\n", .{comma});
    }
};

fn pipeline(a: Allocator, w: *Writer, f: *const Function) !void {
    var entries: std.ArrayList(Entry) = .empty;
    for ([_][]const Arg{ f.required_args, f.optional_args }, 0..) |args, pass| {
        for (args) |arg| {
            var key = Line.init(a);
            try argKey(key.w(), arg.gql_name);
            try entries.append(a, if (pass == 0) try requiredEntry(a, key.text(), arg) else try optionalEntry(a, key.text(), arg));
        }
    }

    var select = Line.init(a);
    try select.w().print("QB.select(\"{s}\"", .{f.gql_name});
    for (entries.items) |e| try select.w().print(", {s}: {s}", .{ e.key, e.value });
    try select.w().writeByte(')');

    const nodes = f.@"return" == .nodes;
    var line = Line.init(a);
    try line.w().print("{s}.query_builder |> {s}{s}", .{ f.self, select.text(), if (nodes) " " ++ select_fields else "" });
    if (line.fits(6)) return w.print("      {s}\n", .{line.text()});

    try w.print("      {s}.query_builder\n", .{f.self});
    if (select.fits(6 + 3)) {
        try w.print("      |> {s}\n", .{select.text()});
    } else {
        try w.print("      |> QB.select(\"{s}\",\n", .{f.gql_name});
        for (entries.items, 0..) |e, i| {
            try pad(w, 8);
            try e.write(w, 8, i + 1 == entries.items.len);
        }
        try w.writeAll("      )\n");
    }
    if (nodes) try w.print("      {s}\n", .{select_fields});
}

// A plain identifier is written bare as a keyword key; anything else is quoted.
fn argKey(w: *Writer, name: []const u8) !void {
    const plain = name.len > 0 and (std.ascii.isLower(name[0]) or name[0] == '_') and for (name[1..]) |c| {
        if (!(std.ascii.isAlphanumeric(c) or c == '_')) break false;
    } else true;
    if (plain) try w.writeAll(name) else try w.print("\"{s}\"", .{name});
}

fn requiredEntry(a: Allocator, key: []const u8, arg: Arg) !Entry {
    return .{ .key = key, .value = switch (types.encoder(arg.type)) {
        .identity => arg.name,
        .call => |fun| try std.fmt.allocPrint(a, "{s}({s})", .{ fun, arg.name }),
        .map => |fun| try std.fmt.allocPrint(a, "Enum.map({s}, &{s}/1)", .{ arg.name, fun }),
    } };
}

fn optionalEntry(a: Allocator, key: []const u8, arg: Arg) !Entry {
    const cond = try std.fmt.allocPrint(a, "optional_args[:{s}]", .{arg.name});
    const then = switch (types.encoder(arg.type)) {
        .identity => return .{ .key = key, .value = cond },
        .call => |fun| try std.fmt.allocPrint(a, "{s}({s})", .{ fun, cond }),
        .map => |fun| try std.fmt.allocPrint(a, "Enum.map({s}, &{s}/1)", .{ cond, fun }),
    };
    return .{
        .key = key,
        .value = try std.fmt.allocPrint(a, "if({s}, do: {s}, else: nil)", .{ cond, then }),
        .cond = cond,
        .then = then,
    };
}

// -- Executing ---------------------------------------------------------------

fn execute(a: Allocator, w: *Writer, f: *const Function) !void {
    const self = f.self;
    switch (f.@"return") {
        .lazy => |t| try w.print(
            \\    %{s}{{
            \\      query_builder: query_builder,
            \\      client: {s}.client
            \\    }}
            \\
        , .{ (try types.module(a, t)).?, self }),
        .leaf => try w.print("    Client.execute({s}.client, query_builder)\n", .{self}),
        .void => try caseExecute(w, self, "{:ok, _}", ":ok"),
        .@"enum" => |t| try caseExecute(w, self, "{:ok, enum}", try std.fmt.allocPrint(a, "{{:ok, {s}.from_string(enum)}}", .{(try types.module(a, t)).?})),
        .list_of_enum => |t| try caseExecute(w, self, "{:ok, enums}", try std.fmt.allocPrint(a, "{{:ok, Enum.map(enums, &{s}.from_string/1)}}", .{(try types.module(a, t)).?})),
        .nodes => |t| {
            const gql_name = switch (types.element(t).?) {
                .object, .interface => |n| n,
                else => unreachable,
            };
            try withHead(w, self, "items");
            try w.writeAll("      {:ok,\n       for %{\"id\" => id} <- items do\n");
            try nodeStruct(w, 9, try naming.module(a, gql_name), gql_name, "QB.query()", self, ".client");
            try w.writeAll("\n       end}\n    end\n");
        },
        .node => |gql_name| {
            try withHead(w, self, "id");
            try w.writeAll("      {:ok,\n");
            try nodeStruct(w, 7, try naming.module(a, gql_name), gql_name, "QB.query()", self, ".client");
            try w.writeAll("}\n    end\n");
        },
    }
}

/// `case Client.execute(...)` with an `{:ok, _}` clause and a pass-through
/// error clause. When the ok clause does not fit on one line, the formatter
/// breaks every clause and separates them with a blank line.
fn caseExecute(w: *Writer, self: []const u8, pattern: []const u8, body: []const u8) !void {
    try w.print("    case Client.execute({s}.client, query_builder) do\n", .{self});
    if (6 + pattern.len + " -> ".len + body.len <= line_length) {
        try w.print("      {s} -> {s}\n      error -> error\n", .{ pattern, body });
    } else {
        try w.print("      {s} ->\n        {s}\n\n      error ->\n        error\n", .{ pattern, body });
    }
    try w.writeAll("    end\n");
}

/// `with {:ok, var} <- Client.execute(...) do`, broken after `<-` when long.
fn withHead(w: *Writer, self: []const u8, variable: []const u8) !void {
    const fixed = "    with {:ok, } <- Client.execute(.client, query_builder)".len;
    const sep: []const u8 = if (fixed + variable.len + self.len <= line_length) " " else "\n           ";
    try w.print("    with {{:ok, {s}}} <-{s}Client.execute({s}.client, query_builder) do\n", .{ variable, sep, self });
}

/// A struct that resolves back to a node by id, starting at column `indent`
/// and ending on its closing brace with no newline.
fn nodeStruct(w: *Writer, indent: usize, module: []const u8, gql_name: []const u8, base: []const u8, client: []const u8, client_suffix: []const u8) !void {
    try pad(w, indent);
    try w.print("%{s}{{\n", .{module});
    try pad(w, indent + 2);
    try w.writeAll("query_builder:\n");
    for ([_][]const u8{ base, "|> QB.select(\"node\", id: id)" }) |part| {
        try pad(w, indent + 4);
        try w.print("{s}\n", .{part});
    }
    try pad(w, indent + 4);
    try w.print("|> QB.inline_fragment(\"{s}\"),\n", .{gql_name});
    try pad(w, indent + 2);
    try w.print("client: {s}{s}\n", .{ client, client_suffix });
    try pad(w, indent);
    try w.writeByte('}');
}

// -- Protocol implementations ------------------------------------------------

/// `Module.id(var)` after `{:ok, id} =`: on the same line, on the next, or with
/// its argument broken out when even that is too long.
fn idCall(a: Allocator, mod: *const ModuleDef, fits: bool) ![]const u8 {
    if (fits) return std.fmt.allocPrint(a, " {s}.id({s})", .{ mod.module, mod.variable });
    if (6 + mod.module.len + ".id()".len + mod.variable.len <= line_length) {
        return std.fmt.allocPrint(a, "\n      {s}.id({s})", .{ mod.module, mod.variable });
    }
    return std.fmt.allocPrint(a, "\n      {s}.id(\n        {s}\n      )", .{ mod.module, mod.variable });
}

fn protocols(a: Allocator, w: *Writer, mod: *const ModuleDef) !void {
    // A multi-line assignment gets a blank line after it.
    const fits = "    {:ok, id} = .id()".len + mod.module.len + mod.variable.len <= line_length;
    try w.print(
        \\
        \\defimpl Jason.Encoder, for: {0s} do
        \\  def encode({1s}, opts) do
        \\    {{:ok, id}} ={2s}
        \\{3s}    Jason.Encode.string(id, opts)
        \\  end
        \\end
        \\
        \\defimpl Nestru.Decoder, for: {0s} do
        \\  def decode_fields_hint(_struct, _context, id) do
        \\    alias Dagger.Core.QueryBuilder, as: QB
        \\    dag = Dagger.Global.dag()
        \\
        \\    {{:ok,
        \\
    , .{
        mod.module,
        mod.variable,
        try idCall(a, mod, fits),
        if (fits) "" else "\n",
    });
    try nodeStruct(w, 5, mod.module, mod.gql_name, "dag.query_builder", "dag.client", "");
    try w.writeAll("}\n  end\nend\n");
}

// -- Documentation -----------------------------------------------------------

/// `attr"""` heredoc with its body indented to match. Blank lines stay empty.
fn heredoc(w: *Writer, indent: usize, attr: []const u8, text: []const u8) !void {
    try pad(w, indent);
    try w.print("{s}\"\"\"\n", .{attr});
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |l| {
        if (l.len > 0) try pad(w, indent);
        var rest = l;
        while (std.mem.indexOfScalar(u8, rest, '\\')) |i| {
            try w.writeAll(rest[0 .. i + 1]);
            try w.writeByte('\\');
            rest = rest[i + 1 ..];
        }
        try w.print("{s}\n", .{rest});
    }
    try pad(w, indent);
    try w.writeAll("\"\"\"\n");
}
