# This file generated by `dagger_codegen`. Please DO NOT EDIT.
defmodule Dagger.Directory do
  @moduledoc """
  A directory.
  """

  use Dagger.Core.Base, kind: :object, name: "Directory"

  alias Dagger.Core.Client
  alias Dagger.Core.QueryBuilder, as: QB

  defstruct [:query_builder, :client]

  @type t() :: %__MODULE__{query_builder: QB.t(), client: Client.t()}

  @doc """
  Return a snapshot with a directory added
  """
  @spec with_directory(t(), String.t(), Dagger.Directory.t(), [
          {:exclude, [String.t()]},
          {:include, [String.t()]},
          {:gitignore, boolean()},
          {:owner, String.t()}
        ]) :: Dagger.Directory.t()
  def with_directory(
        %__MODULE__{} = directory,
        path,
        %Dagger.Directory{} = source,
        optional_args \\ []
      )
      when is_binary(path) do
    query_builder =
      directory.query_builder
      |> QB.select("withDirectory",
        path: path,
        source: Dagger.ID.id!(source),
        exclude: optional_args[:exclude],
        include: optional_args[:include],
        gitignore: optional_args[:gitignore],
        owner: optional_args[:owner]
      )

    %Dagger.Directory{
      query_builder: query_builder,
      client: directory.client
    }
  end
end
